name: On master & Publish

on:
  push:
    paths: "libs/**"
    branches: [master, next]

jobs:
  dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: |-
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Npm Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

  # sonarcloud:
  #     name: Sonar Scan
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 0
  #       - name: SonarCloud Scan
  #         uses: sonarsource/sonarcloud-github-action@master
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run linting
        run: npm run affected:lint -- --base=origin/master~1

  test:
    name: Test applications & libraries
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run tests
        run: npm run affected:test -- --base=origin/master~1

  publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Publish
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - name: Setup Node.js with Npm Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run builders Affected. Run many?
        run: npm run nx run-many -- --parallel --maxParallel=5 --target build --with-deps --all --verbose

        # run: npm run affected:build -- --base=origin/master~1 --prod --with-deps
      - name: Run Semantic Release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
