name: On master & Publish

on:
  push:
    paths: 'libs/**'
    branches: [master, next]

jobs:
  dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

  # sonarcloud:
  #     name: Sonar Scan
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 0
  #       - name: SonarCloud Scan
  #         uses: sonarsource/sonarcloud-github-action@master
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@master
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run linting
        run: yarn affected:lint --base=origin/master~1

  test:
    name: Test applications & libraries
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@master
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run tests
        run: yarn affected:test --base=origin/master~1

  publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Publish
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@master
        with:
          ref: master

      - run: git fetch --no-tags --prune --depth=5 origin master

      - name: Setup Node.js with Npm Package Registry
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run builders Affected. Run many?
        run: yarn nx run-many --parallel --maxParallel=5 --target build --with-deps --all --verbose

        # run: yarn affected:build --base=origin/master~1 --prod --with-deps
      - name: Run Semantic Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
