name: Pull Request on master

on:
  pull_request:
    paths: "libs/**"
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Npm Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

  # sonarcloud:
  #     name: Sonar Scan
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 0
  #       - name: SonarCloud Scan
  #         uses: sonarsource/sonarcloud-github-action@master
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build applications & libraries
    runs-on: ubuntu-latest
    # needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # - name: Restore dependencies from cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Install NX globally
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      #   run: npm install -g @nrwl/cli
      - run: npm install
      - name: Run builders
        run: npm run nx affected:build -- --base=origin/master --head=${{ github.event.pull_request.head.ref }} --prod --with-deps

  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run linting
        run: npm run affected:lint --base=origin/master --head=${{ github.event.pull_request.head.ref }}

  test:
    name: Test applications & libraries
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run tests
        run: npm run affected:test --base=origin/master --head=${{ github.event.pull_request.head.ref }}
